- hosts: webservers
  tasks:
  - name: install httpd
    package:
      name: "httpd"
      state: present
 - name: install php
   package:
     name: "php"
     state: present
 - name: deployment of webserver
  copy:
    src: "index.php"
    dest: "/var/www/html"
 - name: start service
   service:
     name: "httpd"
     state: restarted
